config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :foods do
    resources :reviews
  end
  root 'foods#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
    has_many :foods
end

app/models/food.rb
class Food < ApplicationRecord
    belongs_to :user
    belongs_to :category
    has_many :reviews
    
    has_attached_file :food_img, :styles => { :food_index => "100x150>", :food_show => "325x475>" }, :default_url => "/images/:style/missing.png"
    validates_attachment_content_type :food_img, :content_type => /\Aimage\/.*\Z/
end

app/models/review.rb
class Review < ApplicationRecord
    belongs_to :food
    belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  has_many :foods
  has_many :reviews
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/foods_controller.rb
class FoodsController < ApplicationController
    before_action :find_food, only: [:show, :edit, :update, :destroy]
    before_action :authenticate_user!, only: [:new, :edit]
    def index
        if params[:category].blank?
            @foods = Food.all.order("created_at DESC")
        else
            @category_id = Category.find_by(name: params[:category]).id
            @foods = Food.where(:category_id => @category_id).order("created_at DESC")
        end
    end
    def show
		if @food.reviews.blank?
			@average_review = 0
		else
			@average_review = @food.reviews.average(:rating).round(2)
		end
	end
    def new
        @food = current_user.foods.build
        @categories = Category.all.map{ |c| [c.name, c.id] }
    end
    def create
        @food =current_user.foods.build(food_params)
        @food.category_id = params[:category_id]
        if @food.save
            redirect_to root_path
        else
            render 'new'
        end
    end
    def edit
        @categories = Category.all.map{ |c| [c.name, c.id] }
    end
    def update
        @food =current_user.foods.build(food_params)
        if @food.update(food_params)
            redirect_to food_path(@food)
        else
            render 'edit'
        end
    end
    def destroy
        @food.destroy
        redirect_to root_path
    end
    private
        def food_params
            params.require(:food).permit(:name, :author, :desciption, :address, :time, :price, :sale, :category_id, :food_img)
        end
        def find_food
            @food = Food.find(params[:id])
        end

end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
    before_action :find_food
    before_action :find_review, only: [:edit, :update, :destroy]
	before_action :authenticate_user!, only: [:new, :edit]

    def new
        @review = Review.new
    end

    def create
        @review = Review.new(review_params)
        @review.food_id = @food.id
        @review.user_id = current_user.id

        if @review.save
            redirect_to food_path(@food)
        else
            render 'new'
        end
    end

    def edit
    end

    def update
		if @review.update(review_params)
			redirect_to food_path(@food)
		else
			render 'edit'
		end
	end

	def destroy
		@review.destroy
		redirect_to food_path(@food)
	end
    private 

    def review_params
        params.require(:review).permit(:rating, :comment)
    end

    def find_food
        @food = Food.find(params[:food_id])
    end

    def find_review
        @review = Review.find(params[:id])
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/foods_helper.rb
module FoodsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/foods/_form.html.erb
<%= simple_form_for @food, :html => { :multipart => true} do |f| %>
    <%= select_tag(:category_id, options_for_select(@categories), :prompt => "Chọn danh mục") %>
    <%= f.file_field :food_img %>
    <%= f.input :name, label:"Tên món:" %>
    <%= f.input :author, label:"Tên quán:"%>
    <%= f.input :desciption, label:"Mô tả:" %>
    <%= f.input :address, label:"Địa chỉ:" %>
    <%= f.input :time, label:"Giờ hoạt động:" %>
    <%= f.input :price, label:"Giá thành:"%>
    <%= f.input :sale, label:"Giảm giá:" %>
    <%= f.button :submit , :class => 'btn-custom2'%>
<% end %>

app/views/foods/edit.html.erb
<div class="col-md-6 col-md-offset-3">

	<div class="new-food-form">
        <h1>Sửa món ăn</h1>
        <%= simple_form_for @food, :html => { :multipart => true} do |f| %>
            <%= f.select :category_id, @categories %>
            <%= f.file_field :food_img %>
            <%= f.input :name, label:"Tên món:" %>
            <%= f.input :author, label:"Tên quán:"%>
            <%= f.input :desciption, label:"Mô tả:" %>
            <%= f.input :address, label:"Địa chỉ:" %>
            <%= f.input :time, label:"Giờ hoạt động:" %>
            <%= f.input :price, label:"Giá thành:"%>
            <%= f.input :sale, label:"Giảm giá:" %>
            <%= f.button :submit, :class => 'btn-custom2' %>
        <% end %>
    </div>
</div>

app/views/foods/index.html.erb
<h1 class="current-category"><%= params[:category] %></h1>

<% if @foods.count == 0 %>

	<h1>There are no books currently in this category</h1>

<% else %>	
	<div class="main-right-home">
		<div class="row">

			<% @foods.each do |food| %>

				<div class="col-md-3">
					<a href="/foods/<%= food.id %>">
						<%= image_tag food.food_img.url(:food_index), class: "food" %>
					</a>
				</div>	

			<% end %>

		</div>
	</div
	
<% end %>	

app/views/foods/new.html.erb
<div class="col-md-6 col-md-offset-3">

	<div class="new-food-form">

		<h1>Món ăn mới</h1>

		<%= render 'form' %>

	</div>

</div>

app/views/foods/show.html.erb
<div class="row">
    <div class="col-md-4">
        <%= image_tag @food.food_img.url(:food_show), class:"food-show" %>
    </div>
    <div class="col-md-8">
        <div class="food-info">
            <h2 class="food-title"><%= @food.name %></h2>
            <h3 class="food-author"><%= @food.author %></h3>
            <h2 class="avg-rating">Average Rating</h2>
            <div class="average-review-rating" data-score=<%= @average_review %>></div>
            <span class="number-of-reviews">dựa trên <%= @food.reviews.count %> reviews</span>
            <h5 class="food-decription">Mô tả: <%= @food.desciption %></h5>
            <h3>Địa chỉ: <%= @food.address %></h3>
            <h3>Mở cửa: <%= @food.time %></h3>
            <h3>Giá: <%= @food.price %></h3>
            <h3>Sale: <%= @food.sale %></h3>
            <h4>Danh mục: <%= @food.category.name %></h4>
        </div>
    </div>
</div>
<div class="row">

	<div class="col-md-4">

		<div class="reviews">
			<h1>Phản hồi</h1>
			<%= render @food.reviews %>

			<div>
				<%= link_to "Thêm bình luận", new_food_review_path(@food), class: "btn-custom" %>
			</div>

		</div>	

	</div>

</div>
<div class="links btn-group">
    <%= link_to "Trở về", root_path , class: "btn btn-custom"%>

    <% if user_signed_in? %>
        <% if @food.user_id == current_user.id %>
            <%= link_to "Chỉnh sửa", edit_food_path(@food), class: "btn btn-custom" %>
            <%= link_to "Xóa", food_path(@food), method: :delete, data: {confirm: "Bạn có muốn xóa #{@food.name} không?"}, class: "btn btn-custom" %>
        <% end %>
    <% end %>
</div>
<script>
	$('.review-rating').raty({
		readOnly: true,
		score: function() {
			return $(this).attr('data-score');
		},
		path: '/assets/'
	});
</script>


<script>
	$('.average-review-rating').raty({
		readOnly: true,
		path: '/assets/',
		score: function() {
			return $(this).attr('data-score')
		}
	});
</script>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>VietFood</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
	
	<nav class="navbar navbar-default">

		<div class="container">

			<div class="navbar-header">
				<%= link_to "VietFood", root_path, class: "navbar-brand" %>
			</div>

			<ul class="nav navbar-nav">
				<li><%= link_to "Đăng ký", new_user_registration_path %></li>
				<% if user_signed_in? %>
					<li><%= link_to "Đăng xuất", destroy_user_session_path, method: :delete %></li>
				<% else %>	
					<li><%= link_to "Đăng nhập", new_user_session_path %></li>
				<% end %>
			</ul>

			<ul class="nav navbar-nav navbar-right">

				<li class="dropdown">
					<a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">Danh mục<span class="caret"></span></a>
					<ul class="dropdown-menu" role="menu">
						<% Category.all.each do |category| %>
							<li class="<%= 'active' if params[:category] == category.name %>">
								<%= link_to category.name, foods_path(category: category.name), class: "link" %>
							</li>
						<% end %>
					</ul>
				</li>


				<% if user_signed_in? %>
					<li><%= link_to "Thêm món ăn", new_food_path %></li>
				<% end %>
				
			</ul>

		</div>

	</nav>

	<p class="notice"><%= notice %></p>
  <p class="alert"><%= alert %></p>

  <div class="container">
		<%= yield %>
	</div>	

</body>
</html>

app/views/reviews/_form.html.erb
<%= simple_form_for([@food, @food.reviews.build]) do |f| %>
	<div id="rating-form">
		<label>Rating</label>
	</div>
	<%= f.input :comment %>
	<%= f.button :submit, :class => "btn-custom2" %>
<% end %>

<script>
	$('#rating-form').raty({
		path: '/assets/',
		scoreName: 'review[rating]'
	});
</script>

app/views/reviews/_review.html.erb
<div class="review">

	<div class="review-rating" data-score="<%= review.rating %>"></div>
	<p class="review-comment"><%= review.comment %></p>


	<% if user_signed_in? %>

		<% if review.user_id == current_user.id %>

			<div class="links btn-group">

				<%= link_to "Chỉnh sửa", edit_food_review_path(review.food, review), class: "btn btn-custom" %>
				<%= link_to "Xóa", food_review_path(review.food, review), method: :delete, data: { confirm: "Bạn có muốn xóa bình luận này không?" }, class: "btn btn-custom" %>

			</div>
		
		<% end %>	

	<% end %>

</div>		

app/views/reviews/edit.html.erb
<div class="col-md-6 col-md-offset-3">

	<div class="edit-review-form">

		<h1>Chỉnh sửa bình luận</h1>

		<%= simple_form_for([@food, @review]) do |f| %>
			<div id="rating-form">
				<label>Rating</label>
			</div>
			<%= f.input :comment %>
			<%= f.button :submit, :class => "btn-custom2" %>
		<% end %>	

	</div>

</div>

<script>
	$('#rating-form').raty({
		path: '/assets/',
		scoreName: 'review[rating]'
	});
</script>

app/views/reviews/new.html.erb
<div class="col-md-6 col-md-offset-3">

	<div class="new-review-form">

		<h1>Bình luận mới</h1>

		<%= render 'form' %>

	</div>

</div>